### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by bdrung** [Andersama/rematrix-filter#10]
This plugin has no license specified. No license means no permissions are granted.

Please add a license file and a license header to the source code file. See https://choosealicense.com/

You could put it under GPL v2 or later (same as OBS) or under a short and permissive license like MIT.

**Comment by Andersama** [comment]
There's virtually no point, the plugin is so simple anyone could recreate this with next to no effort at any given time. It's CC as far as I'm concerned.

**Comment by bdrung** [comment]
Can you add that information (CC license) to the project (i.e. source code files and/or README)?

**Comment by fGeorjje** [comment]
Having this officially licensed would mean much easier inclusion in other open source projects.
(since it links with OBS it'd have to be GPL anyway)
