### ISSUE TITLE
ZIP has only the locale ini file

### ISSUE THREAD

**Issue by Saxtus** [Andersama/rematrix-filter#3]
Hello,

Unfortunately, the latest ZIP release doesn't have the win prebuilt plugin. I.e. obs-studio\obs-plugins 32 and 64 bit directories are empty.

**Comment by Andersama** [comment]
Thank you for the heads up, it completed the build, but apparently I'm going to have to do a bit more work on the automation script again. Seems the build wasn't copied into place.

**Comment by Andersama** [comment]
It looks like I got it to complete the build again, and it also looks like the copy worked this time* May take a bit, I'm away from my main computer here, unreliable internet's taking it's toll.

**Comment by Andersama** [comment]
Both releases should be up w/ their respective .dll's momentarily.
